version: '3'
services:
   noding:
      image: 'registry.gitlab.com/juanjmerono/noding:master'
      networks:
        - noding-network
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 30s
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
      environment:
        - SERVICE_PORTS=3000

   lb:
      image: 'dockercloud/haproxy:latest'
      networks:
        - noding-network
      links:
        - noding
      depends_on:
        - noding
      environment:
        - BALANCE=roundrobin
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - '8080:80'
      deploy:
        placement:
          constraints: [node.role == manager]

networks:
  noding-network:
