version: '3'
services:
   socat:
      image: 'alpine/socat:latest'
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - '2376:2375'
      command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
